version: '3.7'

services:
  gc-system-payment-container:
    image: gcsystempayment
    build:
      context: .
      target: development
    env_file:
      - ./env/development.env
    ports:
      - "8081:8081"
      - "8001:8001"
    volumes:
      - certificates:/app/certificates
volumes:
  certificates: